### PR TITLE
Refer to idr0037 in the screen description

### PR DESCRIPTION
**Pull request by sbesson**
The upcoming release of the [idr0037-vigilante-hipsci](https://github.com/IDR/idr0037-vigilante-hipsci) study will contain all the data included in this study and effectively supersedes it.

Immediately, this tries to reformulate the `Screen description` which will be available from https://idr.openmicroscopy.org/webclient/?show=screen-1901 to indicate this concept.

### CODE REVIEW

**Review by francesw — CHANGES_REQUESTED** [review]
I would change "An extended version of this screen is now available including all the data from this study. Please refer to idr0037-vigilante-hipsci for more details." to "This screen has now been extended to include all data from this study.  Please refer to idr0037-vigilante-hipsci for more details."

**Review by francesw — CHANGES_REQUESTED** [review]
I would also change "have been released at this time (May 2017)" to "were released in May 2017."

**Comment by sbesson** [comment]
As per what has been done for [other studies](https://github.com/search?q=org%3AIDR+Study+Version+History&type=Code), I would propose migrating this to a `Study Version History` fields and have its own paragraph in the description on IDR. Thought?

**Comment by francesw** [comment]
I think it's a good idea to have it in Study Version History, similar to other studies.  

Suggested wording: In February 2019, this screen was extended and 87 human induced pluripotent stem cell lines from 62 donors were added.  All data from this study is included in idr0037-vigilante-hipsci.

**Comment by francesw** [comment]
:+1:

**Pull request merged**
